//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.MvcWebUI.DB
{
    using System;
    
    public enum MemberTypes : int
    {
        Customer = 7,
        Editor = 8,
        Admin = 10
    }
}
